### ISSUE TITLE
Delete Parameters in Backend Listener not working

### ISSUE THREAD

**Issue by QAInsights** [dynatrace-oss/jmeter-dynatrace-plugin#3]
Deleting any parameter in the backend listener, not actually deleting it. 

**Steps to reproduce:**
1. Add a backend listener and select `com.dynatrace.jmeter.plugins.MintBackendListener`
2. Delete any parameter(s)
3. Click on any other element in the test plan
4. Click on the backend listener again, you could see the deleted parameters are added again.

**Comment by christian-inzko-dt** [comment]
The parameters are provided as default parameters by implementing the https://jmeter.apache.org/api/org/apache/jmeter/visualizers/backend/BackendListenerClient.html#getDefaultParameters--

Thats the reason why they are added again when you delete them. I have found no possibility in the JMeter Backend listener API to change this behavior. I found it easer to provide all the required parameter keys as default parameters instead of just specifying them in the docs.

But you can modify those parameters and remove/replace the parts which you don't need.
For the transactionDimensions the default "dt.entity.service=SERVICE-XXXXXXXXXXXXX" is ignored when sending the dimemsions for the metrics to dynatrace so you can also leave it and the other parameters are required anyway.

If this behavior is ok for you, i will close the issue?

**Comment by QAInsights** [comment]
Thanks @christian-inzko-dt for the clarification. I think that would be fine. I am closing this issue. :)
